"""empty message

Revision ID: 153c0663899d
Revises: None
Create Date: 2016-03-28 18:24:09.770396

"""

# revision identifiers, used by Alembic.
revision = '153c0663899d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('checked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'checked')
    ### end Alembic commands ###
