"""empty message

Revision ID: f66415f87c55
Revises: 153c0663899d
Create Date: 2016-03-28 21:00:46.348173

"""

# revision identifiers, used by Alembic.
revision = 'f66415f87c55'
down_revision = '153c0663899d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('mail', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'mail')
    ### end Alembic commands ###
